apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hotstat-helm
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chintu-cloud/kubernetes-Helm.git
    targetRevision: main
    path: project-2
    helm:
      releaseName: hotstat
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: hotstar

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
